
import gui.MyGUI;
import java.awt.AWTEvent;
import java.awt.AWTException;
import java.awt.Point;
import java.awt.Robot;
import java.awt.event.AWTEventListener;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JTextField;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wxw18
 */
public class AnimationFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnimationFrame
     */
    ArrayList<AWTEvent> alae = new ArrayList<>();
    
    //From lab 4 - store first four mouse presses
    ArrayList<AWTEvent> al = new ArrayList<>();
    
    Robot robot;

    public AnimationFrame() {
        initComponents();
        try {
            robot = new Robot();
            robot.setAutoWaitForIdle(true);
        } catch (AWTException ex) {
            Logger.getLogger(AnimationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Toolkit tk = Toolkit.getDefaultToolkit();
        AWTEventListener listener = new MyAWTEventListener(alae, al);
        tk.addAWTEventListener(listener, AWTEvent.MOUSE_EVENT_MASK + AWTEvent.MOUSE_MOTION_EVENT_MASK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordJButton = new javax.swing.JButton();
        stopJButton = new javax.swing.JButton();
        playJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recordJButton.setText("Record");

        stopJButton.setText("Stop");

        playJButton.setText("Play");
        playJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playJButton)
                    .addComponent(stopJButton)
                    .addComponent(recordJButton))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(recordJButton)
                .addGap(18, 18, 18)
                .addComponent(stopJButton)
                .addGap(18, 18, 18)
                .addComponent(playJButton)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playJButtonActionPerformed
        Runnable run = () -> {
            try{
            //prev lab
            JTextField jtf1 =
                    (JTextField) al.get(0).getSource();

            JTextField jtf2 =
                    (JTextField) al.get(1).getSource();

            JTextField jtf3 =
                    (JTextField) al.get(2).getSource();

            JButton jb =
                    (JButton) al.get(3).getSource();
            
            jtf1.setText("0");
            jtf2.setText("0");
             
            BufferedReader br =
                    new BufferedReader(
                            new FileReader("input.txt"));

            String line;
            
            //set test cases to 0 
            int n = 0;            
            
            while ((line = br.readLine()) != null && n < 10) {
                //previous lab
                String[] values =
                        line.trim().split("\\s+");

                String num1 = values[0];
                String num2 = values[1];
                String expected = values[2];

                jtf1.setText(num1);
                jtf2.setText(num2);
                
                //store time of previos mouse event. 
                //set to 0 for start = 0 means we have not yet handled first event
                long prevTime = 0;
                
                for (AWTEvent event: alae){
                    //cast the events as mouse events
                    MouseEvent me = (MouseEvent) event;
                
                    //if first event skip
                    if (prevTime !=0){
                        //calculate time passed between events
                        long delay = me.getWhen() - prevTime;
                        
                        //copy delay time to robot time delay
                        if(delay>0){
                            robot.delay((int) delay);
                        }
                    }

                    //make prevTime this event time
                    prevTime = me.getWhen();
                        
                    //replay mouse movements
                    if (me.getID()==MouseEvent.MOUSE_MOVED){
                        Point point = me.getLocationOnScreen();
                        robot.mouseMove(point.x, point.y);
                    }
                
                    //replay mouse presses
                    if (me.getID()==MouseEvent.MOUSE_PRESSED){                   
                        if (me.getButton()==MouseEvent.BUTTON1){
                            robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
                            robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
                        }
                    } 
                }  
                 
                //previous lab
                Thread.sleep(100);
                String actual =
                        jtf3.getText().trim();
                System.out.println(
                        actual.equals(expected));

                n++;
                }
            
            br.close();
            
            }catch (Exception e) {
                e.printStackTrace();
            }
        };
        
        Thread thread = new Thread(run);
        thread.start();
    }//GEN-LAST:event_playJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MyGUI gui = new MyGUI();

                gui.setSize(400, 300);
                gui.setVisible(true);
                
                new AnimationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton playJButton;
    private javax.swing.JButton recordJButton;
    private javax.swing.JButton stopJButton;
    // End of variables declaration//GEN-END:variables
}
